### ISSUE TITLE
SMTP AUTH Issue - Email Notification not working

### ISSUE THREAD

**Issue by Pixelartist** [getsentry/docker-sentry#102]
Hello,

I tried various attempts but it seems the email notification is broken on the latest docker image. I will list the version I am using and the error which is appearing.

Sentry 8.14.1 (pulled by sentry:latest)

If you enter a smtp server (like googlemail):
```
 mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
 mail.host: 'smtp.gmail.com'
 mail.port: 587
 mail.username: 'account@gmail.com'
 mail.password: 'crazypassword'
 mail.use-tls: true
# The email address to send on behalf of
 mail.from: 'account@gmail.com'
```

The test email works .. I received it. As soon as it is supposed to send the normal email, like user registration, one of the sentry workers kicks in and spits out this:

```
4/6/2017 5:00:38 PMTraceback (most recent call last):
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
4/6/2017 5:00:38 PM    R = retval = fun(*args, **kwargs)
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
4/6/2017 5:00:38 PM    return self.run(*args, **kwargs)
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
4/6/2017 5:00:38 PM    result = func(*args, **kwargs)
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/email.py", line 72, in send_email
4/6/2017 5:00:38 PM    send_messages([message])
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/sentry/utils/email.py", line 405, in send_messages
4/6/2017 5:00:38 PM    sent = connection.send_messages(messages)
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 87, in send_messages
4/6/2017 5:00:38 PM    new_conn_created = self.open()
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 54, in open
4/6/2017 5:00:38 PM    self.connection.login(self.username, self.password)
4/6/2017 5:00:38 PM  File "/usr/local/lib/python2.7/smtplib.py", line 585, in login
4/6/2017 5:00:38 PM    raise SMTPException("SMTP AUTH extension not supported by server.")
4/6/2017 5:00:38 PMSMTPException: SMTP AUTH extension not supported by server.
4/6/2017 5:00:38 PM15:00:38 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[a98ab5c8-1f4a-47e4-b28f-586daaa718a9] raised unexpected: SMTPException('SMTP AUTH extension not supported by server.',) (data={u'hostname': 'celery@2d7da40bc6fb', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7fd77d1c69d0>}", u'id': 'a98ab5c8-1f4a-47e4-b28f-586daaa718a9'})
```

Any support on fixing this is appreciated.

**Comment by Pixelartist** [comment]
Hello again,

in this case it was one celery worker not fetching the config file for the email. This is why the test email worked but not the one which gets send trough the worker.

**Comment by Loliko-Kai** [comment]
I get the same issues,can you tell me how to fix it? Thank you

**Comment by Pixelartist** [comment]
Hello, if I remember correctly you need to restart the worker which is not being synced. You should tap into the container and check if it received the correct configuration to verify if you encounter the same issue as I did.
