### ISSUE TITLE
UnicodeDecodeError when running sentry upgrade

### ISSUE THREAD

**Issue by unclegaara** [getsentry/docker-sentry#120]
I have a problem with sentry:8.22-onbuild
Trying to run:
`docker run --rm -it mysentry:latest sentry upgrade`
Crashed with error:

> Traceback (most recent call last):
>   File "/usr/local/bin/sentry", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 158, in main
>     cli(prog_name=get_prog(), obj={}, max_content_width=100)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
>     return ctx.invoke(f, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
>     _upgrade(not noinput, traceback, verbosity, not no_repair)
>   File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 20, in _upgrade
>     verbosity=verbosity,
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
>     return klass.execute(*args, **defaults)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
>     return self.handle_noargs(**options)
>   File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
>     syncdb.Command().execute(**options)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
>     return self.handle_noargs(**options)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
>     cursor = connection.cursor()
>   File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 162, in cursor
>     cursor = util.CursorWrapper(self._cursor(), self)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 44, in inner
>     if not can_reconnect(e):
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/helpers.py", line 20, in can_reconnect
>     exc_msg = six.text_type(exc)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
> 

Docker version 17.09.1-ce, build 19e2cf6
Postgresql 10.1:
Encoding: UTF8
LC_COLLATE: en_US.utf8
LC_CTYPE: en_US.utf8

**Comment by BYK** [comment]
Closing this due to inactivity and staleness. Please file a new issue with a more recent release if you are still having this issue.
