### ISSUE TITLE
Docs not built

### ISSUE THREAD

**Issue by qbright** [getsentry/docker-sentry#178]
i am build the docker image by the `https://github.com/getsentry/docker-sentry/tree/master/git` and run the image but throw the error like 

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/project_docs.py", line 14, in get
    raise RuntimeError('Docs not built')
RuntimeError: Docs not built`

**Comment by BYK** [comment]
Hi, the recommended usage is either pulling the built image from Docker Hub or using the "official" onpremise repo here: https://github.com/getsentry/onpremise/
