### ISSUE TITLE
No default org created

### ISSUE THREAD

**Issue by Spellchaser** [getsentry/docker-sentry#199]
Followed the instructions for docker afaik. When I try to hit the login page I get an error
```
Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
```
The `sentry_organization` table is empty
`SENTRY_SINGLE_ORGANIZATION=True` from the defaults

Traces from the web pod
```
172.17.0.1 - - [15/Aug/2019:21:35:32 +0000] "GET /auth/login/ HTTP/1.1" 500 5580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
127.0.0.1 - - [16/Aug/2019:14:21:55 +0000] "GET /auth/login HTTP/1.1" 301 275 "-" "curl/7.52.1"
172.17.0.1 - - [16/Aug/2019:14:22:07 +0000] "GET / HTTP/1.1" 302 467 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
14:22:07 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
172.17.0.1 - - [16/Aug/2019:14:22:07 +0000] "GET /auth/login/ HTTP/1.1" 500 5580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
```

docker ps
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
f5eab8338199        sentry              "/entrypoint.sh run …"   47 hours ago        Up 47 hours         0.0.0.0:9000->9000/tcp   sentry-web-01
41243a2c2d1b        tianon/exim4        "docker-entrypoint.s…"   2 days ago          Up 2 days           25/tcp                   sentry-smtp
de52acb1befe        postgres:9.5        "docker-entrypoint.s…"   2 days ago          Up 2 days           5432/tcp                 sentry-postgres
819a11e4bc86        redis:3.2-alpine    "docker-entrypoint.s…"   2 days ago          Up 2 days           6379/tcp                 sentry-redis
```

docker version
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

psql
```
sentry=# \dt sentry_organization
               List of relations
 Schema |        Name         | Type  | Owner  
--------+---------------------+-------+--------
 public | sentry_organization | table | sentry
(1 row)

sentry=# SELECT * FROM sentry_organization;
 id | name | status | date_added | slug | flags | default_role 
----+------+--------+------------+------+-------+--------------
(0 rows)
```

**Comment by Spellchaser** [comment]
Will post in getsentry/sentry :)
