### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by lenovouser** [getsentry/docker-sentry#46]
When I first setup my container like this:

```
docker run --name log -it --rm \
-e SENTRY_SECRET_KEY=<key> \
-e SENTRY_DB_USER=sentry \
-e SENTRY_DB_PASSWORD=<password> \
-e SENTRY_DB_NAME=sentry \
--link postgresql:postgres \
--link redis:redis \
sentry:8.1.2 upgrade
```

it fails with this:

````
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 44, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "sentry_project" does not exist
LINE 1: ...ct"."status", "sentry_project"."first_event" FROM "sentry_pr...
                                                             ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 145, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 25, in inner
    configure()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 108, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 313, in configure
    }, skip_backend_validation=skip_backend_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 158, in initialize_app
    validate_backends()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 181, in validate_backends
    backend.validate()
  File "/usr/local/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 155, in validate
    label='Digests',
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 73, in check_cluster_versions
    recommended,
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/versioning.py", line 45, in check_versions
    raise InvalidConfiguration(make_upgrade_message(service, 'must', required, must_upgrade))
sentry.exceptions.InvalidConfiguration: Redis (Digests) must be upgraded to 2.8.9 on redis:6379.
```

**Comment by mattrobenolt** [comment]
You can't run upgrade because the version of redis being used is too old. The error message is pretty clear.

`sentry.exceptions.InvalidConfiguration: Redis (Digests) must be upgraded to 2.8.9 on redis:6379.`

This is preventing upgrade to run. These requirements are documented here: https://docs.getsentry.com/on-premise/server/installation/
