### ISSUE TITLE
Running 8.5: Unable to increment internal metric

### ISSUE THREAD

**Issue by micheee** [getsentry/docker-sentry#73]
(Sorry in advance if this is the wrong place to ask).

I tried to setup sentry as described on Dockerhub:

```
    docker run -d --name sentry-redis redis
    docker run -d --name sentry-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres


    SENTRY_SECRET_KEY=$(docker run --rm sentry generate-secret-key)



    docker run -it --rm -e SENTRY_SECRET_KEY="$SENTRY_SECRET_KEY" --link sentry-postgres:postgres --link sentry-redis:redis sentry sentry upgrade

    docker run -d --name my-sentry -p 8080:9000 -e SENTRY_SECRET_KEY="$SENTRY_SECRET_KEY" --link sentry-redis:redis --link sentry-postgres:postgres sentry
    docker run -d --name sentry-celery-beat -e SENTRY_SECRET_KEY="$SENTRY_SECRET_KEY" --link sentry-postgres:postgres --link sentry-redis:redis sentry run cron
    docker run -d --name sentry-celery1 -e SENTRY_SECRET_KEY="$SENTRY_SECRET_KEY" --link sentry-postgres:postgres --link sentry-redis:redis sentry run worker

```

I setup a super-user and and copy the tracking code.
I then start tracking an error, with the Javascript client, it seems to work at first, but the error shows up nowhere.

Instead the following shows up: ![image](https://cloud.githubusercontent.com/assets/422242/15795721/91561d4a-29f4-11e6-8da2-0a36eb10208c.png)

`docker logs sentry-celery1` shows the following errors:

```bash
[2016-06-03 23:27:43,262: ERROR/MainProcess] Hard time limit (65s) exceeded for sentry.tasks.store.preprocess_event[db4c3534-b88e-44a6-b9e7-5093f03724ad]
[ERROR] Unable to incr internal metric
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 53, in _incr_internal
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 147, in incr
    self.incr_multi([(model, key)], timestamp, count)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 169, in incr_multi
    self.calculate_expiry(rollup, max_values, timestamp),
  File "/usr/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 577, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 358, in join
    command_buffer.send_pending_requests()
  File "/usr/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 185, in send_pending_requests
    send_buffer(self._send_buf, self.connection._sock, self.host_id)
  File "/usr/local/lib/python2.7/site-packages/sentry/../rb/clients.py", line 63, in send_buffer
    % (host_id, e))
ConnectionError: Error while writing to socket (host 0): [Errno 32] Broken pipe
```

**Comment by micheee** [comment]
Nervermind, I had Javascript scraping enabled and sentry was not able to connect to the host containing the JS-files.
